"""Add quiz_attempt table

Revision ID: d2590025dd8c
Revises: 3acfdd3ae172
Create Date: 2025-04-24 18:03:02.961596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2590025dd8c'
down_revision: Union[str, None] = '3acfdd3ae172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
